project_id = "iwgtwzpygoyohocbgqgm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbuckets]
enabled = true
port = 54324

[storage]
enabled = true
port = 54325

[auth]
enabled = true
port = 54326

[edge-runtime]
enabled = true
port = 54327

[functions.fetch-rss-posts]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.update-rss-images]
verify_jwt = false