// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwgtwzpygoyohocbgqgm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3Z3R3enB5Z295b2hvY2JncWdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTM4OTksImV4cCI6MjA2NzEyOTg5OX0.qAe2WDhB0K3r71mKwAFBXL9_gc2sPn8XwgM6mAS9iyI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});